### ISSUE TITLE
Panic on assignment to entry in nil map at `streamsMap.AddStream`

### ISSUE THREAD

**Issue by masih** [quic-go/webtransport-go#66]
On new session [`handleConn`](https://github.com/masih/webtransport-go/blob/72455c5fd07be29cacc64e9b1b99435c881dc060/session.go#L114) eventually [closes the session](https://github.com/masih/webtransport-go/blob/72455c5fd07be29cacc64e9b1b99435c881dc060/session.go#L130) executed in a goroutine. As part of this closure, `streamsMap` [is set to `nil`](https://github.com/masih/webtransport-go/blob/f892c8f3d7806ca5bae004ac9c2f533876883ba9/streams_map.go#L41).

I wonder if it is possible for session manager to return a session that is already closed, which could then result in a panic below.

```
panic: assignment to entry in nil map
goroutine 2004647120 [running]:
github.com/quic-go/webtransport-go.(*streamsMap).AddStream(0xc194fdbde8, 0xc15f2954a0?, 0xc025dc8b70)
	/go/pkg/mod/github.com/quic-go/webtransport-go@v0.5.1/streams_map.go:24 +0x66
github.com/quic-go/webtransport-go.(*Session).addStream(0xc194fdbd10, {0x7f2b66fb6cf0?, 0xc15f2954a0}, 0x60?)
	/go/pkg/mod/github.com/quic-go/webtransport-go@v0.5.1/session.go:173 +0x152
github.com/quic-go/webtransport-go.(*Session).OpenStreamSync(0xc194fdbd10, {0x136cb60?, 0xc087ad9920?})
	/go/pkg/mod/github.com/quic-go/webtransport-go@v0.5.1/session.go:324 +0x21e
github.com/libp2p/go-libp2p/p2p/transport/webtransport.(*conn).OpenStream(0x4b23f034feb1?, {0x136cb60?, 0xc087ad9920?})
	/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/transport/webtransport/conn.go:48 +0x2b
github.com/libp2p/go-libp2p/p2p/net/swarm.(*Conn).openAndAddStream(0xc0d09e8ab0, {0x136cb60?, 0xc087ad9920?}, {0x1376500, 0x1d05f40})
	/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/net/swarm/swarm_conn.go:220 +0x42
github.com/libp2p/go-libp2p/p2p/net/swarm.(*Conn).NewStream(0xc0d09e8ab0, {0x136cb60, 0xc087ad9920})
	/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/net/swarm/swarm_conn.go:211 +0x175
github.com/libp2p/go-libp2p/p2p/net/swarm.(*Swarm).NewStream(0xc000726000, {0x136cb60, 0xc087ad9920}, {0xc2252abad0, 0x26})
	/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/net/swarm/swarm.go:401 +0x1f0
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).NewStream(0xc00027e780, {0x136cb60, 0xc087ad9920}, {0xc2252abad0, 0x26}, {0xc000868070?, 0x1, 0x1})
	/go/pkg/mod/github.com/libp2p/go-libp2p@v0.25.1/p2p/host/basic/basic_host.go:626 +0x16f
github.com/libp2p/go-libp2p-kad-dht/internal/net.(*peerMessageSender).prep(0xc23c3a3ae0, {0x136cb60?, 0xc087ad9920?})
	/go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.21.0/internal/net/message_manager.go:218 +0x6a
github.com/libp2p/go-libp2p-kad-dht/internal/net.(*peerMessageSender).prepOrInvalidate(0xc23c3a3ae0, {0x136cb60, 0xc087ad9920})
	/go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.21.0/internal/net/message_manager.go:200 +0x91
github.com/libp2p/go-libp2p-kad-dht/internal/net.(*messageSenderImpl).messageSenderForPeer(0xc000d88e00, {0x136cb60, 0xc087ad9920}, {0xc2252abad0, 0x26})
	/go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.21.0/internal/net/message_manager.go:150 +0x233
github.com/libp2p/go-libp2p-kad-dht/internal/net.(*messageSenderImpl).SendRequest(0xc000d88e00, {0x136cab8, 0xc16b6a9b40}, {0xc2252abad0, 0x26}, 0xe50620?)
	/go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.21.0/internal/net/message_manager.go:78 +0xd8
github.com/libp2p/go-libp2p-kad-dht/pb.(*ProtocolMessenger).GetClosestPeers(0xc000868130, {0x136cab8, 0xc16b6a9b40}, {0xc2252abad0, 0x26}, {0xc0633607b0?, 0x0?})
	/go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.21.0/pb/protocol_messenger.go:108 +0xd4
github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).FindPeer.func1({0x136cab8, 0xc16b6a9b40}, {0xc2252abad0, 0x26})
	/go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.21.0/routing.go:604 +0xfb
github.com/libp2p/go-libp2p-kad-dht.(*query).queryPeer(0xc1920f7cb0, {0x136cab8, 0xc16b6a9b40}, 0xc02ce7d120?, {0xc2252abad0, 0x26})
	/go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.21.0/query.go:408 +0x26e
created by github.com/libp2p/go-libp2p-kad-dht.(*query).spawnQuery
	/go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.21.0/query.go:325 +0x44a
```

**Comment by marten-seemann** [comment]
That's an interesting one! The reason here is that `OpenStreamSync` can block at the QUIC layer. We need to check if the session is still alive after this call has returned.

Fix incoming.
