### ISSUE TITLE
goroutine leak in runSendQueue

### ISSUE THREAD

**Issue by hareku** [quic-go/webtransport-go#98]
`go.uber.org/goleak` detected a goroutine leak. I'd appreciate it if you could investigate this issue.

Code: https://github.com/aptpod/webtransport-go/commit/fd28449c965e65b9cbb18c6760de1398bf5780df

Result:
```
--- FAIL: TestUnidirectionalStreams (0.70s)
    d:\Code\github\webtransport-go\webtransport_test.go:328: found unexpected goroutines:
        [Goroutine 77 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
        goroutine 77 [IO wait]:
        internal/poll.runtime_pollWait(0x222ec317ee8, 0x72)
        	C:/Program Files/Go/src/runtime/netpoll.go:343 +0x85
        internal/poll.(*pollDesc).wait(0xc000404798?, 0xc000507b38?, 0x0)
        	C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:84 +0x27
        internal/poll.execIO(0xc000404798, 0x10c1118)
        	C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0xe6
        internal/poll.(*FD).ReadFromInet6(0xc000404780, {0xc0001eb800, 0xc000121b00?, 0xc000507c20?}, 0xc000507c78)
        	C:/Program Files/Go/src/internal/poll/fd_windows.go:637 +0x145
        net.(*netFD).readFromInet6(0xc000404780, {0xc0001eb800?, 0xc0001209c0?, 0xc000507c60?}, 0xc971ba?)
        	C:/Program Files/Go/src/net/fd_posix.go:72 +0x25
        net.(*UDPConn).readFrom(0x30?, {0xc0001eb800?, 0xc0002868d0?, 0x0?}, 0xc0002868d0)
        	C:/Program Files/Go/src/net/udpsock_posix.go:59 +0x79
        net.(*UDPConn).readFromUDP(0xc0000980b8, {0xc0001eb800?, 0x4?, 0x1046ec0?}, 0x4?)
        	C:/Program Files/Go/src/net/udpsock.go:149 +0x30
        net.(*UDPConn).ReadFrom(0x13930a0?, {0xc0001eb800, 0x5ac, 0x5ac})
        	C:/Program Files/Go/src/net/udpsock.go:158 +0x4a
        github.com/quic-go/quic-go.(*basicConn).ReadPacket(0xc0001180d8)
        	C:/Users/user/go/pkg/mod/github.com/quic-go/quic-go@v0.39.0/sys_conn.go:95 +0xab
        github.com/quic-go/quic-go.(*Transport).listen(0xc000416000, {0x11246a8, 0xc0001180d8})
        	C:/Users/user/go/pkg/mod/github.com/quic-go/quic-go@v0.39.0/transport.go:338 +0x172
        created by github.com/quic-go/quic-go.(*Transport).init.func1 in goroutine 6
        	C:/Users/user/go/pkg/mod/github.com/quic-go/quic-go@v0.39.0/transport.go:242 +0x450
        
         Goroutine 78 in state select, with github.com/quic-go/quic-go.(*Transport).runSendQueue on top of the stack:
        goroutine 78 [select]:
        github.com/quic-go/quic-go.(*Transport).runSendQueue(0xc000416000)
        	C:/Users/user/go/pkg/mod/github.com/quic-go/quic-go@v0.39.0/transport.go:267 +0x107
        created by github.com/quic-go/quic-go.(*Transport).init.func1 in goroutine 6
        	C:/Users/user/go/pkg/mod/github.com/quic-go/quic-go@v0.39.0/transport.go:243 +0x48c
        ]
FAIL
FAIL	github.com/quic-go/webtransport-go	0.997s
FAIL
```

**Comment by marten-seemann** [comment]
Is this because the CONNECTION_CLOSE takes a while to propagate to the peer and close its connection?

**Comment by hareku** [comment]
FYI: Closing `http3.RoundTripper` makes this test passed. https://github.com/aptpod/webtransport-go/commit/75f9de612d0e5b669d40fe39f196aa0db3d64e9d

**Comment by marten-seemann** [comment]
> FYI: Closing `http3.RoundTripper` makes this test passed. [aptpod@75f9de6](https://github.com/aptpod/webtransport-go/commit/75f9de612d0e5b669d40fe39f196aa0db3d64e9d)

@hareku Would you mind sending this change as a PR?
